name: productive
description: Discipline

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  google_fonts: ^1.1.0
  flutter_svg: ^0.17.4
  lottie: ^0.4.0+1

  #Architecture
  rxdart: ^0.24.1
  get_it: ^4.0.2
  provider: ^4.1.3

  #Utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/paper_plane.json
    - assets/images/google.svg

# fonts Balsamiq+Sans, Poppins, Tenali, Rubik, Patrick Hand, Lobster two, Handlee, El Messiri, Alice,
# Amaranth, Comic neue, Jost, Capriola, Combo, Reem Kufi, Cabin Sketch,Caladea,Cinzel, Cousard,Sen,
# Delius, Metrophobic,Pompiere, Gabriela,Kurale,Vioada Libre,Amarante,Soloway,

