name: productive
description: Discipline

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  google_fonts: ^1.1.1
  flutter_svg: ^0.19.1
  lottie: ^0.7.0+1

  #Architecture
  rxdart: ^0.24.1
  get_it: ^5.0.1
  provider: ^4.3.2+2

  #Utils
  dartx: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/

  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product_Sans_Regular.ttf
        - asset: assets/fonts/Product_Sans_Bold.ttf
        - asset: assets/fonts/Product_Sans_Italic.ttf
          style: italic
        - asset: assets/fonts/Product_Sans_Bold_Italic.ttf
          style: italic



# fonts Balsamiq+Sans, Poppins, Tenali, Rubik, Patrick Hand, Lobster two, Handlee, El Messiri, Alice,
# Amaranth, Comic neue, Jost, Capriola, Combo, Reem Kufi, Cabin Sketch,Caladea,Cinzel, Cousard,Sen,
# Delius, Metrophobic,Pompiere, Gabriela,Kurale,Vioada Libre,Amarante,Soloway,

