name: productive
description: Discipline

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  google_fonts: ^1.1.0
  flutter_svg: ^0.17.4
  lottie: ^0.4.0+1
  cached_network_image: ^2.2.0+1

  #Architecture
  rxdart: ^0.24.1
  get_it: ^4.0.2
  provider: ^4.1.3

  #Utils
  dartx: ^0.4.2
  assets_audio_player: ^2.0.6+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/
    - assets/sounds/

  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product_Sans_Regular.ttf
        - asset: assets/fonts/Product_Sans_Bold.ttf
        - asset: assets/fonts/Product_Sans_Italic.ttf
          style: italic
        - asset: assets/fonts/Product_Sans_Bold_Italic.ttf
          style: italic



# fonts Balsamiq+Sans, Poppins, Tenali, Rubik, Patrick Hand, Lobster two, Handlee, El Messiri, Alice,
# Amaranth, Comic neue, Jost, Capriola, Combo, Reem Kufi, Cabin Sketch,Caladea,Cinzel, Cousard,Sen,
# Delius, Metrophobic,Pompiere, Gabriela,Kurale,Vioada Libre,Amarante,Soloway,

